export const SITE = {
  name: "Servchip",
  companyName: "Servchip",
  tagline: "Powering the Future of AI Computing",
  email: "sales@servchip.com",
  phone: "+91 7982498712",
  phoneLink: "+917982498712",
  url: "https://servchip.com",
  defaultTitle:
    "Enterprise Chip Distributor | NVIDIA, AMD & Intel AI Chips | Servchip",
  defaultDescription:
    "Servchip: ISO 9001 certified enterprise chip distributor supplying NVIDIA H100, AMD Instinct MI300X, Intel Xeon & Gaudi 3 accelerators to India & UAE.",
  defaultKeywords: [
    "enterprise chip distributor",
    "buy AI chips",
    "NVIDIA H100 distributor India",
    "NVIDIA GPU supplier UAE",
    "AMD Instinct distributor",
    "semiconductor procurement services",
    "AI accelerator distributor UAE",
    "Data center GPU distributor in UAE",
    "HBM memory supplier",
    "GPU server supplier India",
    "AI chip distributor UAE",
    "NVIDIA Supplier in Dubai",
    "NVIDIA Supplier in UAE",
    "NVIDIA Authorized Dealer in UAE",
    "AMD Authorized Distributor in UAE",
    "AMD Authorized Distributor in USA",
    "AMD Supplier in UAE",
    "Intel Authorized Distributor in UAE",
    "Intel Supplier in UAE",
    "Intel Supplier in Dubai",
    "HPC chip distributor UAE",
    "HPC chip distributor Dubai",
    "AI chip distributor USA",
    "DATA center GPU Distributor & Supplier USA",
    "DATA center GPU Distributor & Supplier UAE",
    "Enterprise Semiconductor Distributor UAE",
    "Enterprise Semiconductor Distributor Dubai",
    "Enterprise Semiconductor Distributor USA",
    "AI chip distributor India",
    "AI chip distributor UAE",
    "AI chip distributor USA",
    "AI chip distributor Dubai",
    "Best AI chip distributor UAE",
    "Best AI chip distributor Dubai",
    "Best AI chip distributor India",
    "Best AI chip distributor USA",
    "Best NVIDIA chip distributor USA",
    "Best NVIDIA chip distributor UAE",
    "Best NVIDIA chip distributor Dubai",
    "Best NVIDIA chip distributor India",
    "Best AMD chip distributor USA",
    "Best AMD chip distributor UAE",
    "Best AMD chip distributor Dubai",
    "Best AMD chip distributor India",
    "Best Intel chip distributor USA",
    "Best Intel chip distributor UAE",
    "Best Intel chip distributor Dubai",
    "Best Intel chip distributor India",
  ],
  addresses: {
    india:
      "A-24/5, 3rd Floor, NH-19, Mohan Cooperative Industrial Estate, New Delhi, Delhi 110044",
    indiaStructured: {
      "@type": "PostalAddress",
      streetAddress:
        "A-24/5, 3rd Floor, NH-19, Mohan Cooperative Industrial Estate",
      addressLocality: "New Delhi",
      addressRegion: "Delhi",
      postalCode: "110044",
      addressCountry: "IN",
    },
    uae: "Business Centre, Sharjah Publishing City Free Zone, Sharjah, United Arab Emirates",
    uaeStructured: {
      "@type": "PostalAddress",
      streetAddress: "Business Centre, Sharjah Publishing City Free Zone",
      addressLocality: "Sharjah",
      addressCountry: "AE",
    },
  },
  social: {
    linkedin: "https://www.linkedin.com/company/servchip",
    twitter: "https://twitter.com/servchip",
    facebook: "https://facebook.com/servchip",
    youtube: "https://youtube.com/@servchip",
    instagram: "https://instagram.com/servchip",
  },
  geo: {
    region: "IN-DL",
    placename: "New Delhi, India",
    position: "28.5245;77.2665",
    latitude: "28.5245",
    longitude: "77.2665",
  },
} as const;

export const BREAKPOINTS = {
  mobile: 768,
  tablet: 1024,
  desktop: 1280,
} as const;

export const SCHEMA = {
  seller: { "@type": "Organization", name: "Servchip Inc." },
  currency: "USD",
  returnPolicy: {
    "@type": "MerchantReturnPolicy",
    applicableCountry: "US",
    returnPolicyCategory: "https://schema.org/MerchantReturnNotPermitted",
  },
  shipping: {
    "@type": "OfferShippingDetails",
    shippingDestination: {
      "@type": "DefinedRegion",
      addressCountry: "US",
    },
    shippingRate: {
      "@type": "MonetaryAmount",
      value: "0",
      currency: "USD",
    },
    deliveryTime: {
      "@type": "ShippingDeliveryTime",
      handlingTime: {
        "@type": "QuantitativeValue",
        minValue: "1",
        maxValue: "3",
        unitCode: "DAY",
      },
      transitTime: {
        "@type": "QuantitativeValue",
        minValue: "3",
        maxValue: "7",
        unitCode: "DAY",
      },
    },
  },
  availabilityMap: {
    in_stock: "https://schema.org/InStock",
    on_order: "https://schema.org/PreOrder",
    limited: "https://schema.org/LimitedAvailability",
    pre_order: "https://schema.org/PreOrder",
    discontinued: "https://schema.org/Discontinued",
  },
  priceValidUntilDays: 365,
} as const;
